import Link from "next/link";
import InteriorShell from "./InteriorShell";
import styles from "./SketchbookEntryPage.module.css";

export default function SketchbookEntryPage() {
  return <InteriorShell>
    <main className={styles.page}>
      <div className={styles.crumb}><Link href="/sketchbook">← SKETCHBOOK</Link><span>/ BATTLE PLANS, FIRST PASS</span><b>ENTRY 004 / LONG NOTE</b></div>
      <header className={styles.lead}><div><span className={styles.kicker}>SEP 24, 2026 / GAME DESIGN / SAMPLE ENTRY</span><h1>Battle plans,<br /><em>first pass.</em></h1><p>Getting a plan into the game is one problem. Letting a player understand it before the fight is another.</p><div className={styles.tags}><Link href="/sketchbook">#pixel-pugilists</Link><Link href="/sketchbook">#game-design</Link></div></div><figure><img src="/media/pp-priority.png" alt="Pixel Pugilists priority builder showing rules and mock battle state" /><figcaption>PRIORITY BUILDER / CURRENT CAPTURE</figcaption></figure></header>
      <nav className={styles.mobileContents} aria-label="In this note"><span>IN THIS NOTE</span><a href="#problem">01 / The screen</a><a href="#tradeoffs">02 / The trade-off</a><a href="#next">03 / What&apos;s next</a></nav>
      <div className={styles.bodyLayout}><article className={styles.article}><p className={styles.opening}>The current Pixel Pugilists build puts priorities, techniques, conditions, and a mock battle state on one screen. That is the useful part of this experiment: the rule and the situation it applies to can be inspected together.</p>
        <h2 id="problem">What the screen is trying to answer</h2><p>A battle plan is a list of decisions made before combat. Each priority asks whether a condition is true, then picks a technique when it is. The player needs enough context to understand which rule will run first and what it could do.</p><p>The builder shows the ordered slots in the middle, the Familiar and its techniques on the left, and available conditions on the right. The mock state gives those conditions something concrete to compare against. This note uses the visible build as its starting point; the final design rationale still needs an author pass.</p>
        <div className={styles.ruleStrip} aria-label="Priority rule example"><span>01 / FIRST MATCH</span><strong>IF: target has Burn</strong><b>→</b><strong>THEN: choose a technique</strong><small>Example structure, not a final game rule</small></div>
        <h2 id="tradeoffs">The trade-off</h2><p>Showing everything together makes the screen dense. Hiding more would make it harder to compare a rule with the Familiar&apos;s available actions. The next pass should decide which details deserve to stay visible while editing, and which ones can wait until a rule is selected.</p><p>The screenshot is useful evidence because it shows the actual pressure: three working areas competing for space, along with a combat preview. A polished diagram would make the idea cleaner, but it would not show the cost of fitting the idea into the game.</p>
        <figure className={styles.detailImage}><img src="/media/pp-priority.png" alt="Full Pixel Pugilists Priority Builder screenshot" /><figcaption>THE CURRENT WORKING SCREEN. THE RULE LIST, TECHNIQUES, AND MOCK STATE ALL NEED ROOM.</figcaption></figure>
        <h2 id="next">What to check next</h2><p>The useful test is whether a player can look at one priority and predict what will happen in a sample situation. If that prediction is hard, the condition labels, ordering, or preview need another pass. The current capture gives a baseline for that comparison.</p><p>This is an early note from the build, not a claim that the interface is finished. The game page has more captures from combat, brackets, and rewards.</p><div className={styles.articleLinks}><Link href="/projects/pixel-pugilists">Open Pixel Pugilists ↗</Link><Link href="/sketchbook">All Sketchbook entries ↗</Link></div></article>
      <aside className={styles.margin}><div className={styles.contents}><span>IN THIS NOTE</span><a href="#problem">01 / The screen</a><a href="#tradeoffs">02 / The trade-off</a><a href="#next">03 / What&apos;s next</a></div><div className={styles.familiarLink}><img src="/media/ashwing.png" alt="" /><span>ASHWING IS ONE OF THE FAMILIARS USING THESE SYSTEMS.</span><Link href="/familiars/ashwing">Open profile ↗</Link></div><div className={styles.draftNote}><span>AUTHOR PASS NEEDED</span><p>This sample text describes the captured build. Exact development history and results should come from the creator.</p></div></aside></div>
      <div className={styles.bottom}><span>END OF ENTRY 004</span><Link href="/sketchbook">← Back to the feed</Link><img src="/media/p03-badge-orange.png" alt="" aria-hidden="true" /></div>
    </main>
  </InteriorShell>;
}
